### ISSUE TITLE
one node of cluster hang when I execute alter table

### ISSUE THREAD

**Issue by caipengtao** [percona/galera#125]
Hi guys,I have 5 nodes in the galera cluster ,I have two problems .

1.Sometimes,I execute alter table to add a column on one node ,the node may be hang,and I cant login in it,but other nodes my be ok,I dont know why I?
2.I make a test,but deadlock occured,I operate on the same node,two sessions,you can see the picture 
<img width="1346" alt="ecbb92bd-737e-4b6b-be7e-997476017cbf" src="https://user-images.githubusercontent.com/19907364/30675159-90eec57c-9eb1-11e7-9c10-004c958cfe70.png">

I hope you can give me some ideas,I'm so sad,thx

**Comment by rameshvs02** [comment]
Hi,

The deadlock issue is expected because ALTER TABLE will be TOI and it takes priority and kill parallel running local transaction. Deadlock is not real deadlock as you in Galera. It is the message that suggests there is a deadlock

Also could not reproduce hang issue with 5 node cluster.
